markdown: kramdown
permalink: /:title.html
url: https://acacool.github.io/
lsi: true
rouge: true
safe: true

# presonal config
title: 宋建军's Blog
feed: /atom.xml
comments: disqus

author:
  name: 宋建军
  nickname: beta
  email: acacool@gmail.com
  gmail: me@gmail.com
  qqmail: http://mail.qq.com/cgi-bin/qm_share?t=qm_mailme&email=GnZzcX94f257WmtrNHl1dw
  qqlist: http://list.qq.com/cgi-bin/qf_invite?id=eff06957927177ae5d491bb3c18e4a3c5fc328c95b6ae04f
  site: https://acacool.github.io/

seo:
  keyword:
  description:
